<script setup lang="ts">
import { useQuery, useQueryClient } from '@tanstack/vue-query'
import type { DataTableColumns } from 'naive-ui'
import { NButton, NDataTable, NFormItem, NInput, NInputNumber, NModal, NSelect, useMessage } from 'naive-ui'
import { h, ref } from 'vue'
import { adminResetPassword, listUsers, type UserUpdate, updateUser } from '@/api/users'
import PageHeader from '@/components/PageHeader.vue'
import { ROLE_LABELS } from '@/config/roles'
import type { User, UserRole, UserStatus } from '@/types/common'

const client=useQueryClient();const message=useMessage()
const page=ref(1);const keyword=ref('');const role=ref<UserRole|''>('');const status=ref<UserStatus|''>('');const pageSize=20
const users=useQuery({queryKey:['users',page,keyword,role,status],queryFn:()=>listUsers({page:page.value,pageSize,keyword:keyword.value||undefined,role:role.value||undefined,status:status.value||undefined})})
const show=ref(false);const resetShow=ref(false);const editing=ref<User|null>(null);const nextRole=ref<UserRole>('member');const nextStatus=ref<UserStatus>('active');const level=ref(1);const newPassword=ref('');const busy=ref(false)
function open(row:User){editing.value=row;nextRole.value=row.role;nextStatus.value=row.status;level.value=row.level;show.value=true}
async function save(){if(!editing.value)return;busy.value=true;const payload:UserUpdate={role:nextRole.value,status:nextStatus.value,level:level.value};try{await updateUser(editing.value.id,payload);message.success('用户信息已更新');show.value=false;await client.invalidateQueries({queryKey:['users']})}catch(e){message.error(e instanceof Error?e.message:'更新失败')}finally{busy.value=false}}
async function reset(){if(!editing.value||newPassword.value.length<8){message.warning('新密码至少 8 位');return}busy.value=true;try{await adminResetPassword(editing.value.id,newPassword.value);message.success('密码已重置，请通过安全渠道告知用户');resetShow.value=false;newPassword.value=''}catch(e){message.error(e instanceof Error?e.message:'重置失败')}finally{busy.value=false}}
const columns:DataTableColumns<User>=[{title:'用户',key:'username',render:r=>h('div',{class:'user-cell'},[h('b',r.nickname||r.username),h('small',`@${r.username}`)])},{title:'邮箱',key:'email',render:r=>r.email||'—'},{title:'角色',key:'role',render:r=>ROLE_LABELS[r.role]},{title:'状态',key:'status',render:r=>r.status==='active'?'正常':'已禁用'},{title:'等级',key:'level',width:80},{title:'注册时间',key:'createdAt',render:r=>r.createdAt?new Date(r.createdAt).toLocaleDateString('zh-CN'):'—'},{title:'操作',key:'actions',width:180,render:r=>h('div',{class:'row-actions'},[h(NButton,{size:'small',quaternary:true,onClick:()=>open(r)},{default:()=> '编辑'}),h(NButton,{size:'small',quaternary:true,onClick:()=>{editing.value=r;resetShow.value=true}},{default:()=> '重置密码'})])}]
</script>
<template><section class="page-content"><PageHeader title="用户管理" description="管理会员角色、账号状态和等级；密码重置不会向页面返回凭证"/><section class="content-card card-padding"><div class="toolbar"><NInput v-model:value="keyword" clearable placeholder="搜索用户名或邮箱" style="max-width:280px" @keyup.enter="users.refetch()"/><NSelect v-model:value="role" :options="[{label:'全部角色',value:''},...Object.entries(ROLE_LABELS).map(([value,label])=>({value,label}))]" style="width:140px"/><NSelect v-model:value="status" :options="[{label:'全部状态',value:''},{label:'正常',value:'active'},{label:'已禁用',value:'disabled'}]" style="width:140px"/><span class="grow"/><NButton @click="users.refetch()">刷新</NButton></div><NDataTable :columns="columns" :data="users.data.value?.list??[]" :loading="users.isPending.value" :scroll-x="1000" :pagination="{page,pageSize,itemCount:users.data.value?.pagination.total??0,onUpdatePage:(n:number)=>page=n}"/></section><NModal v-model:show="show" preset="card" title="编辑用户" style="width:min(500px,calc(100vw - 32px))"><div class="form-stack"><p>账号：{{editing?.username}}</p><NFormItem label="角色"><NSelect v-model:value="nextRole" :options="Object.entries(ROLE_LABELS).map(([value,label])=>({value,label}))"/></NFormItem><NFormItem label="状态"><NSelect v-model:value="nextStatus" :options="[{label:'正常',value:'active'},{label:'已禁用',value:'disabled'}]"/></NFormItem><NFormItem label="会员等级"><NInputNumber v-model:value="level" :min="1"/></NFormItem></div><template #footer><div class="modal-actions"><NButton @click="show=false">取消</NButton><NButton type="primary" :loading="busy" @click="save">保存</NButton></div></template></NModal><NModal v-model:show="resetShow" preset="card" title="重置用户密码" style="width:min(500px,calc(100vw - 32px))"><p>为 {{editing?.username}} 设置新密码，重置后该用户所有已登录设备都会失效。</p><NInput v-model:value="newPassword" type="password" show-password-on="click" minlength="8" placeholder="至少 8 位新密码"/><template #footer><div class="modal-actions"><NButton @click="resetShow=false">取消</NButton><NButton type="warning" :loading="busy" @click="reset">确认重置</NButton></div></template></NModal></section></template>
<style scoped>.user-cell{display:grid;gap:4px}.user-cell small{color:#8894a5}.row-actions,.modal-actions{display:flex;justify-content:flex-end;gap:6px}.form-stack{display:grid;gap:14px}.form-stack label{display:grid;gap:6px;color:#58677b;font-size:13px}</style>
